window.LESSON = {
  introExamples: [
    ["I'd like to eat.", "Tôi muốn ăn."],
    ["I'd like to drink some water.", "Tôi muốn uống chút nước."],
    ["I'd like to go home.", "Tôi muốn về nhà."],
    ["I'd like to buy this.", "Tôi muốn mua cái này."],
    ["I'd like to ask you something.", "Tôi muốn hỏi bạn một việc."]
  ],
  sentences20: [
    ["I'd like to eat.", "Tôi muốn ăn."],
    ["I'd like to drink something.", "Tôi muốn uống gì đó."],
    ["I'd like to go home.", "Tôi muốn về nhà."],
    ["I'd like to sleep.", "Tôi muốn ngủ."],
    ["I'd like to take a break.", "Tôi muốn nghỉ một chút."],
    ["I'd like to buy this.", "Tôi muốn mua cái này."],
    ["I'd like to try this.", "Tôi muốn thử cái này."],
    ["I'd like to see it.", "Tôi muốn xem nó."],
    ["I'd like to know more.", "Tôi muốn biết thêm."],
    ["I'd like to ask you something.", "Tôi muốn hỏi bạn một chuyện."],
    ["I'd like to talk to you.", "Tôi muốn nói chuyện với bạn."],
    ["I'd like to speak English better.", "Tôi muốn nói tiếng Anh tốt hơn."],
    ["I'd like to learn English.", "Tôi muốn học tiếng Anh."],
    ["I'd like to practice English.", "Tôi muốn luyện tiếng Anh."],
    ["I'd like to make a reservation.", "Tôi muốn đặt chỗ."],
    ["I'd like to order this.", "Tôi muốn gọi món này."],
    ["I'd like to pay by card.", "Tôi muốn thanh toán bằng thẻ."],
    ["I'd like to change my reservation.", "Tôi muốn thay đổi đặt chỗ."],
    ["I'd like to check something.", "Tôi muốn kiểm tra một việc."],
    ["I'd like to explain something.", "Tôi muốn giải thích một việc."]
  ],
  work: [
    ["I'd like to check something.", "Tôi muốn kiểm tra một việc."],
    ["I'd like to confirm one thing.", "Tôi muốn xác nhận một việc."],
    ["I'd like to ask you a question.", "Tôi muốn hỏi bạn một câu."],
    ["I'd like to explain the issue.", "Tôi muốn giải thích vấn đề."],
    ["I'd like to show you something.", "Tôi muốn cho bạn xem một thứ."],
    ["I'd like to discuss this issue.", "Tôi muốn thảo luận vấn đề này."]
  ],
  restaurantNouns: [
    ["I'd like some water.", "Tôi muốn một ít nước."],
    ["I'd like a coffee.", "Tôi muốn một cốc cà phê."],
    ["I'd like this one.", "Tôi muốn cái này."]
  ],
  buildSteps: [
    ["BƯỚC 1", "I'd like to go.", "Tôi muốn đi."],
    ["BƯỚC 2", "I'd like to go there.", "Tôi muốn đến đó."],
    ["BƯỚC 3", "I'd like to go there tomorrow.", "Tôi muốn đến đó ngày mai."],
    ["BƯỚC 4", "I'd like to go there tomorrow with my family.", "Tôi muốn đến đó ngày mai cùng gia đình."]
  ],
  dialogs: [
    { place: "Ở cửa hàng", rows: [["Staff", "How can I help you?", "Tôi có thể giúp gì cho bạn?"], ["You", "I'd like to buy this.", "Tôi muốn mua cái này."]] },
    { place: "Ở khách sạn", rows: [["Staff", "How can I help you?", "Tôi có thể giúp gì cho bạn?"], ["You", "I'd like to check in.", "Tôi muốn làm thủ tục nhận phòng."]] },
    { place: "Ở nhà hàng", rows: [["Staff", "Are you ready to order?", "Bạn sẵn sàng gọi món chưa?"], ["You", "Yes. I'd like to order this.", "Vâng. Tôi muốn gọi món này."]] },
    { place: "Trong công việc", rows: [["Colleague", "Do you have any questions?", "Bạn có câu hỏi nào không?"], ["You", "Yes. I'd like to ask you something.", "Vâng. Tôi muốn hỏi bạn một việc."]] }
  ],
  questions: [
    ["Would you like to sit down?", "Bạn có muốn ngồi xuống không?"],
    ["Would you like to try it?", "Bạn có muốn thử không?"],
    ["Would you like to come with us?", "Bạn có muốn đi cùng chúng tôi không?"]
  ],
  practice: [
    ["Tôi muốn về nhà.", "I'd like to go home."],
    ["Tôi muốn uống nước.", "I'd like to drink some water."],
    ["Tôi muốn mua cái này.", "I'd like to buy this."],
    ["Tôi muốn hỏi bạn một câu.", "I'd like to ask you a question."],
    ["Tôi muốn kiểm tra một việc.", "I'd like to check something."],
    ["Tôi muốn học tiếng Anh.", "I'd like to learn English."],
    ["Tôi muốn nói tiếng Anh tốt hơn.", "I'd like to speak English better."],
    ["Tôi muốn đặt chỗ.", "I'd like to make a reservation."],
    ["Tôi muốn thử cái này.", "I'd like to try this."],
    ["Tôi muốn nói chuyện với bạn.", "I'd like to talk to you."]
  ],
  dailyFive: [
    "I'd like to go home.",
    "I'd like to buy this.",
    "I'd like to ask you something.",
    "I'd like to check something.",
    "I'd like to know more."
  ],
  builderGroups: [
    { label: "Động từ", options: ["go", "eat", "drink", "buy", "try", "ask", "check", "learn", "practice", "order"] },
    { label: "Bổ sung", options: ["home", "there", "this", "some water", "you something", "English", "a coffee", "a question", "more"] },
    { label: "Thời gian / người", options: ["tomorrow", "today", "now", "with my family", "with you"] }
  ],
  dictionary: {
    "i'd": ["/aɪd/", "I would (dạng rút gọn)", "I'd like to go home."],
    "like": ["/laɪk/", "thích; trong 'would like' = muốn", "I'd like some water."],
    "to": ["/tə/", "đến; để; dấu hiệu trước động từ nguyên mẫu", "I'd like to go."],
    "eat": ["/iːt/", "ăn", "I'd like to eat."],
    "drink": ["/drɪŋk/", "uống", "I'd like to drink some water."],
    "water": ["/ˈwɔːtər/", "nước", "I'd like some water."],
    "go": ["/ɡoʊ/", "đi", "I'd like to go home."],
    "home": ["/hoʊm/", "nhà; về nhà", "I'd like to go home."],
    "buy": ["/baɪ/", "mua", "I'd like to buy this."],
    "this": ["/ðɪs/", "cái này; điều này", "I'd like to buy this."],
    "ask": ["/æsk/", "hỏi", "I'd like to ask you something."],
    "something": ["/ˈsʌmθɪŋ/", "một điều gì đó", "I'd like to check something."],
    "sleep": ["/sliːp/", "ngủ", "I'd like to sleep."],
    "take": ["/teɪk/", "lấy; dùng; thực hiện", "I'd like to take a break."],
    "break": ["/breɪk/", "giờ nghỉ; sự nghỉ", "Let's take a break."],
    "try": ["/traɪ/", "thử", "I'd like to try this."],
    "see": ["/siː/", "xem; nhìn thấy", "I'd like to see it."],
    "know": ["/noʊ/", "biết", "I'd like to know more."],
    "more": ["/mɔːr/", "thêm; nhiều hơn", "I'd like to know more."],
    "talk": ["/tɔːk/", "nói chuyện", "I'd like to talk to you."],
    "speak": ["/spiːk/", "nói (một ngôn ngữ)", "I'd like to speak English better."],
    "english": ["/ˈɪŋɡlɪʃ/", "tiếng Anh", "I'd like to learn English."],
    "better": ["/ˈbetər/", "tốt hơn", "I'd like to speak English better."],
    "learn": ["/lɜːrn/", "học", "I'd like to learn English."],
    "practice": ["/ˈpræktɪs/", "luyện tập", "I'd like to practice English."],
    "make": ["/meɪk/", "làm; tạo; thực hiện", "I'd like to make a reservation."],
    "reservation": ["/ˌrezərˈveɪʃən/", "sự đặt chỗ", "I'd like to make a reservation."],
    "order": ["/ˈɔːrdər/", "gọi món; đặt hàng", "I'd like to order this."],
    "pay": ["/peɪ/", "thanh toán", "I'd like to pay by card."],
    "card": ["/kɑːrd/", "thẻ", "I'd like to pay by card."],
    "change": ["/tʃeɪndʒ/", "thay đổi", "I'd like to change my reservation."],
    "check": ["/tʃek/", "kiểm tra", "I'd like to check something."],
    "explain": ["/ɪkˈspleɪn/", "giải thích", "I'd like to explain the issue."],
    "confirm": ["/kənˈfɜːrm/", "xác nhận", "I'd like to confirm one thing."],
    "question": ["/ˈkwestʃən/", "câu hỏi", "I'd like to ask you a question."],
    "issue": ["/ˈɪʃuː/", "vấn đề", "I'd like to explain the issue."],
    "show": ["/ʃoʊ/", "cho xem; chỉ cho", "I'd like to show you something."],
    "discuss": ["/dɪˈskʌs/", "thảo luận", "I'd like to discuss this issue."],
    "coffee": ["/ˈkɔːfi/", "cà phê", "I'd like a coffee."],
    "there": ["/ðer/", "ở đó; đến đó", "I'd like to go there."],
    "tomorrow": ["/təˈmɑːroʊ/", "ngày mai", "I'd like to go there tomorrow."],
    "family": ["/ˈfæməli/", "gia đình", "with my family"],
    "would": ["/wʊd/", "would; trong 'would like' dùng để nói mong muốn lịch sự", "Would you like to try it?"],
    "sit": ["/sɪt/", "ngồi", "Would you like to sit down?"],
    "down": ["/daʊn/", "xuống", "Sit down, please."],
    "come": ["/kʌm/", "đến; đi cùng về phía người nói", "Would you like to come with us?"],
    "with": ["/wɪð/", "với; cùng", "with my family"],
    "us": ["/ʌs/", "chúng tôi / chúng ta (tân ngữ)", "Come with us."],
    "ready": ["/ˈredi/", "sẵn sàng", "Are you ready to order?"],
    "help": ["/help/", "giúp đỡ", "How can I help you?"],
    "have": ["/hæv/", "có", "Do you have any questions?"],
    "any": ["/ˈeni/", "bất kỳ; nào", "Do you have any questions?"]
  },
  phrases: {
    "i'd like to": ["/aɪd laɪk tə/", "tôi muốn... / tôi muốn được...", "I'd like to go home."],
    "would like to": ["/wʊd laɪk tə/", "muốn... (lịch sự)", "Would you like to try it?"],
    "take a break": ["/teɪk ə breɪk/", "nghỉ một chút / nghỉ giải lao", "I'd like to take a break."],
    "go home": ["/ɡoʊ hoʊm/", "về nhà", "I'd like to go home."],
    "pay by card": ["/peɪ baɪ kɑːrd/", "thanh toán bằng thẻ", "I'd like to pay by card."],
    "make a reservation": ["/meɪk ə ˌrezərˈveɪʃən/", "đặt chỗ", "I'd like to make a reservation."],
    "check in": ["/tʃek ɪn/", "làm thủ tục nhận phòng / check-in", "I'd like to check in."],
    "talk to": ["/tɔːk tə/", "nói chuyện với", "I'd like to talk to you."],
    "some water": ["/sʌm ˈwɔːtər/", "một ít nước", "I'd like some water."],
    "a coffee": ["/ə ˈkɔːfi/", "một cốc cà phê", "I'd like a coffee."],
    "this one": ["/ðɪs wʌn/", "cái này", "I'd like this one."],
    "with my family": ["/wɪð maɪ ˈfæməli/", "cùng gia đình tôi", "I'd like to go there tomorrow with my family."],
    "are you ready to order": ["/ɑːr juː ˈredi tə ˈɔːrdər/", "Bạn sẵn sàng gọi món chưa?", "Are you ready to order?"],
    "how can i help you": ["/haʊ kæn aɪ help juː/", "Tôi có thể giúp gì cho bạn?", "How can I help you?"],
    "do you have any questions": ["/duː juː hæv ˈeni ˈkwestʃənz/", "Bạn có câu hỏi nào không?", "Do you have any questions?"]
  }
};
